// Theme definitions and logic
const themeVars = {
    light: {
        '--bg-color': '#F5F5F5',
        '--container-bg': '#FFFFFF',
        '--text-color-primary': '#333333',
        '--text-color-secondary': '#666666',
        '--border-color': '#DDDDDD',
        '--card-bg': '#FFFFFF',
        '--chart-bg': '#F5F5F5',
        '--input-bg': '#FFFFFF',
        '--list-item-bg': '#FFFFFF',
        '--sidebar-bg': '#F5F5F5',
        '--sidebar-text': '#333333',
        '--sidebar-hover-bg': '#EEEEEE',
        '--sidebar-active-bg': '#DDDDDD',
        '--sidebar-active-text': '#333333',
        '--theme-toggle-color': '#333333',
    },
    dark: {
        '--bg-color': '#302d2dff',
        '--container-bg': '#232323ff',
        '--text-color-primary': '#F5F5F5',
        '--text-color-secondary': '#CCCCCC',
        '--border-color': '#444444',
        '--card-bg': '#444444',
        '--chart-bg': '#333333',
        '--input-bg': '#444444',
        '--list-item-bg': '#444444',
        '--sidebar-bg': '#333333',
        '--sidebar-text': '#F5F5F5',
        '--sidebar-hover-bg': '#444444',
        '--sidebar-active-bg': '#555555',
        '--sidebar-active-text': '#F5F5F5',
        '--theme-toggle-color': '#F5F5F5',
    },
    blue: {
        '--bg-color': '#e3f0ff',
        '--container-bg': '#f5fbff',
        '--text-color-primary': '#1e3a5c',
        '--text-color-secondary': '#3b82f6',
        '--border-color': '#60a5fa',
        '--card-bg': '#f0f6ff',
        '--chart-bg': '#e0eaff',
        '--input-bg': '#e0eaff',
        '--list-item-bg': '#e0eaff',
        '--sidebar-bg': '#e0eaff',
        '--sidebar-text': '#1e3a5c',
        '--sidebar-hover-bg': '#bae6fd',
        '--sidebar-active-bg': '#60a5fa',
        '--sidebar-active-text': '#1e40af',
        '--theme-toggle-color': '#2563eb',
    },
    slate: {
        '--bg-color': '#f1f5f9',
        '--container-bg': '#e2e8f0',
        '--text-color-primary': '#334155',
        '--text-color-secondary': '#64748b',
        '--border-color': '#cbd5e1',
        '--card-bg': '#e2e8f0',
        '--chart-bg': '#e2e8f0',
        '--input-bg': '#e2e8f0',
        '--list-item-bg': '#e2e8f0',
        '--sidebar-bg': '#e2e8f0',
        '--sidebar-text': '#334155',
        '--sidebar-hover-bg': '#cbd5e1',
        '--sidebar-active-bg': '#64748b',
        '--sidebar-active-text': '#334155',
        '--theme-toggle-color': '#475569',
    },
    purple: {
        '--bg-color': '#f3e8ff',
        '--container-bg': '#faf5ff',
        '--text-color-primary': '#6d28d9',
        '--text-color-secondary': '#a78bfa',
        '--border-color': '#c4b5fd',
        '--card-bg': '#ede9fe',
        '--chart-bg': '#ede9fe',
        '--input-bg': '#ede9fe',
        '--list-item-bg': '#ede9fe',
        '--sidebar-bg': '#ede9fe',
        '--sidebar-text': '#6d28d9',
        '--sidebar-hover-bg': '#ddd6fe',
        '--sidebar-active-bg': '#a78bfa',
        '--sidebar-active-text': '#6d28d9',
        '--theme-toggle-color': '#a21caf',
    },
    red: {
        '--bg-color': '#fff1f2',
        '--container-bg': '#ffe4e6',
        '--text-color-primary': '#b91c1c',
        '--text-color-secondary': '#f87171',
        '--border-color': '#fca5a5',
        '--card-bg': '#fee2e2',
        '--chart-bg': '#fee2e2',
        '--input-bg': '#fee2e2',
        '--list-item-bg': '#fee2e2',
        '--sidebar-bg': '#fee2e2',
        '--sidebar-text': '#b91c1c',
        '--sidebar-hover-bg': '#fecaca',
        '--sidebar-active-bg': '#f87171',
        '--sidebar-active-text': '#b91c1c',
        '--theme-toggle-color': '#dc2626',
    },
    classicBlue: {
        '--bg-color': '#F5F5F5',
        '--container-bg': '#FFFFFF',
        '--text-color-primary': '#103766',
        '--text-color-secondary': '#288cfa',
        '--border-color': '#288cfa',
        '--card-bg': '#FFFFFF',
        '--chart-bg': '#F5F5F5',
        '--input-bg': '#FFFFFF',
        '--list-item-bg': '#FFFFFF',
        '--sidebar-bg': '#F5F5F5',
        '--sidebar-text': '#103766',
        '--sidebar-hover-bg': '#e6f0fa',
        '--sidebar-active-bg': '#288cfa',
        '--sidebar-active-text': '#FFFFFF',
        '--theme-toggle-color': '#288cfa',
    },
    performanceGreen: {
        '--bg-color': '#F5F5F5',
        '--container-bg': '#FFFFFF',
        '--text-color-primary': '#296346',
        '--text-color-secondary': '#2E865F',
        '--border-color': '#2E865F',
        '--card-bg': '#FFFFFF',
        '--chart-bg': '#C6F4D6',
        '--input-bg': '#FFFFFF',
        '--list-item-bg': '#C6F4D6',
        '--sidebar-bg': '#C6F4D6',
        '--sidebar-text': '#296346',
        '--sidebar-hover-bg': '#e6f9ee',
        '--sidebar-active-bg': '#2E865F',
        '--sidebar-active-text': '#FFFFFF',
        '--theme-toggle-color': '#2E865F',
    },
    trackerBlues: {
        '--bg-color': '#F5F5F5',
        '--container-bg': '#FFFFFF',
        '--text-color-primary': '#1072a6',
        '--text-color-secondary': '#10a6f5',
        '--border-color': '#10a6f5',
        '--card-bg': '#73c9f8',
        '--chart-bg': '#eaf6fc',
        '--input-bg': '#FFFFFF',
        '--list-item-bg': '#eaf6fc',
        '--sidebar-bg': '#73c9f8',
        '--sidebar-text': '#1072a6',
        '--sidebar-hover-bg': '#d2eefd',
        '--sidebar-active-bg': '#10a6f5',
        '--sidebar-active-text': '#FFFFFF',
        '--theme-toggle-color': '#10a6f5',
    },
    financeGreens: {
        '--bg-color': '#F5F5F5',
        '--container-bg': '#FFFFFF',
        '--text-color-primary': '#296346',
        '--text-color-secondary': '#2f9062',
        '--border-color': '#2f9062',
        '--card-bg': '#9bdebe',
        '--chart-bg': '#e6f7ef',
        '--input-bg': '#FFFFFF',
        '--list-item-bg': '#9bdebe',
        '--sidebar-bg': '#9bdebe',
        '--sidebar-text': '#296346',
        '--sidebar-hover-bg': '#d3f3e2',
        '--sidebar-active-bg': '#2f9062',
        '--sidebar-active-text': '#FFFFFF',
        '--theme-toggle-color': '#2f9062',
    },
    accentRed: {
        '--bg-color': '#F5F5F5',
        '--container-bg': '#FFFFFF',
        '--text-color-primary': '#a5270f',
        '--text-color-secondary': '#a5270f',
        '--border-color': '#a5270f',
        '--card-bg': '#FFFFFF',
        '--chart-bg': '#ffeaea',
        '--input-bg': '#FFFFFF',
        '--list-item-bg': '#ffeaea',
        '--sidebar-bg': '#ffeaea',
        '--sidebar-text': '#a5270f',
        '--sidebar-hover-bg': '#f8d3ce',
        '--sidebar-active-bg': '#a5270f',
        '--sidebar-active-text': '#FFFFFF',
        '--theme-toggle-color': '#a5270f',
    },
    royalblue: {
        '--bg-color': '#F5F5F5',
        '--container-bg': '#FFFFFF',
        '--text-color-primary': '#1e3a5c',
        '--text-color-secondary': '#2563eb',
        '--border-color': '#2563eb',
        '--card-bg': '#FFFFFF',
        '--chart-bg': '#e0eaff',
        '--input-bg': '#FFFFFF',
        '--list-item-bg': '#e0eaff',
        '--sidebar-bg': '#e0eaff',
        '--sidebar-text': '#1e3a5c',
        '--sidebar-hover-bg': '#cbd5fd',
        '--sidebar-active-bg': '#2563eb',
        '--sidebar-active-text': '#FFFFFF',
        '--theme-toggle-color': '#2563eb',
 
    },
};

export function applyTheme(theme) {
    const vars = themeVars[theme] || themeVars.light;
    Object.keys(vars).forEach(key => {
        document.documentElement.style.setProperty(key, vars[key]);
    });
    // For dark mode class toggling
    if (theme === 'dark') {
        document.body.classList.add('dark-mode');
    } else {
        document.body.classList.remove('dark-mode');
    }
    localStorage.setItem('selectedTheme', theme);
}
